version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    restart: always
    depends_on:
      - postgres
    entrypoint:  ["./wait-for.sh", "postgres:5432", "--"]
    command: [/main]
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=transaction_system
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data



